##############
## Rules
## swiftlint rules で確認できる
#############

#closing_brace
#colon
#comma
#conditional_binding_cascade
#control_statement
#custom_rules
#cyclomatic_complexity
#empty_count
#file_length
#force_cast
#force_try
#force_unwrapping
#function_body_length
#function_parameter_count
#leading_whitespace
#legacy_cggeometry_functions
#legacy_constant
#legacy_constructor
#line_length
#missing_docs
#nesting
#opening_brace
#operator_whitespace
#return_arrow_whitespace
#statement_position
#todo
#trailing_newline
#trailing_semicolon
#trailing_whitespace
#type_body_length
#type_name
#valid_docs
#variable_name



## デフォルトで無効のものを有効にするルール
opt_in_rules:
- trailing_newline

## 無効にするルール
disabled_rules:
- trailing_whitespace
- type_name
- force_cast
- type_body_length
- file_length
- variable_name
- cyclomatic_complexity
- valid_docs
- missing_docs
- opening_brace
- line_length


force_try: warning

line_length: 200

excluded: # Lint対象から外すファイルのあるパスを記述
- Pods
- Carthage

# 関数の長さ
function_body_length:
- 300 # warning
- 500 # error

# 引数の数
function_parameter_count:
- 10 #warning
- 15 #error
